### ISSUE TITLE
優良顧客判定モデル、退会者判定モデルのオプションを 10 個から 30 個へ変更

### ISSUE THREAD

**Issue by takizawa-cognirobo** [CogniroboInc/cognimaker#19]
https://trello.com/c/qR6AC84C/6-%E5%84%AA%E8%89%AF%E9%A1%A7%E5%AE%A2%E5%88%A4%E5%AE%9A%E3%83%A2%E3%83%87%E3%83%AB%E3%80%81%E9%80%80%E4%BC%9A%E8%80%85%E5%88%A4%E5%AE%9A%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92-10-%E5%80%8B%E3%81%8B%E3%82%89-30-%E5%80%8B%E3%81%B8%E5%A4%89%E6%9B%B4%E3%80%82

こちらのcognimakerでの対応

オプションで与えられるカラムに対応する

**Comment by takizawa-cognirobo** [comment]
**cognimaker側の仕様（案）**

オプションのカラムはCSVダウンロードを行った段階で、以下のようなカラム名になっていることが望ましい。
prefix_(連番1), prefix_(連番2),・・・
prefixはモデルのyamlで指定した名称とする。
cognimakerでは指定したprefixがついているカラムを取得し、そのカラムのリスト内にある各カラムに対して処理を行う。

**懸念点**

- CSVダウンローダーで上記の実装が可能か（WEBからのパラメータで対応が可能か）
- 推論時、追加学習時のパラメータをどうするか？（学習時と同様の処理が可能か？）

**Comment by JunyaKaneko** [comment]
WEB -> Downloader に渡される情報

```
[
    {
        "model_column": "モデルカラム名1", 
        "raw_column": ["実カラム名1", "実カラム名2"],
    },
    {
        "model_column": "モデルカラム名2",
        "raw_column": "実カラム名3", 
    }
]
```

**Comment by JunyaKaneko** [comment]
別話: データの数がゼロになったときの対応。

**Comment by dsonoda** [comment]
2020/3/10 mtgより
![IMG_5310](https://user-images.githubusercontent.com/14954207/76279051-a473e600-62d0-11ea-96a4-866bdc6806ef.JPG)
