### ISSUE TITLE
提案：モデル評価

### ISSUE THREAD

**Issue by joseph-cogni** [CogniroboInc/cognimaker#34]
モデル評価について提案させてください。

### 概要

まず、現状の`train()`と`calc_indicators()`をほぼそのまま使います。末端クラス（○○Estimator）の
`fit()`メソッドはモデルの学習のみ行ってモデルを返します。末端クラスには新たに **choose_evaluation()** メソッドを実装してもらいます。このメソッドの返り値はデータの量などを
加味してCross Validationかtrain-testスプリットかを選択するための辞書オブジェクトです。trainメソッドではchoose_evaluationを呼び出しての返り値にそってCross Validationでの評価もしくはtrain_test_splitでの評価を行います。

指標の計算の時はまずtrainメソッド内でget_predictionから予測値を取得してからcalc_indicatorsなどを呼び出し、真の値と一緒に予測値も渡すように変えます。

### 課題：追加学習

追加学習の場合、同じ評価の仕方で問題ないか

### 課題：ハイパーパラメータのためのスコアの算出

calc_indicatorsに統合できたらいい気がしますが無理でしょうか？

### 実装の例

````python

class BaseEstimator():
  def choose_cross_validation(self, num_splits=5):
    return dict(method='cv', num_splits=num_splits)
  def choose_test_split(self, test_size=0.2):
    return dict(method='split',  test_size=test_size)
  @abstract
  def choose_evaluation(self, num_rows, ...):
    raise NotImplemented()
  def train(self, ):
  ...
  eval_method = self.choose_evaluation(X.shape[0])
  if eval_method['method'] == 'cv':
    <do cross_validation>
  elif eval_method['method'] == 'split':
    X_train, y_train, X_test, y_test = train_test_split(X, y, ...)
    ...
    proba = self.get_predict_proba(model, X_test)
    pred = np.round(proba) 
````

@takizawa-cognirobo @JunyaKaneko いかがでしょうか？

**Comment by takizawa-cognirobo** [comment]
@joseph-cogni 
モデル評価についてのご提案ありがとうございます。
基本的には提案いただいた内容で実装可能かと思います。
挙げていただいた課題について、

>課題：追加学習
追加学習の場合、同じ評価の仕方で問題ないか

→学習済みのモデルをクロスバリデーションごとに読み込むようにすれば可能かと思います。

>課題：ハイパーパラメータのためのスコアの算出
calc_indicatorsに統合できたらいい気がしますが無理でしょうか？

→ハイパーパラメータのスコア算出はSgaeMakerの仕様上必須になります。
指標の算出（calc_indicators）はモデルごとに算出可能な指標も違うという認識なので、分けています。
どちらもクロスバリデーションを入れる場合は、各イテレーションの指標の平均（混同行列の場合は、合計）を指標とする必要があるかと思います。

@JunyaKaneko 
上記の内容で如何でしょうか？
